### ISSUE TITLE
Error when try to start image

### ISSUE THREAD

**Issue by daventt** [adoptium/containers#688]
**What are you trying to do?**

When try to start image with docker compose, i receive following error: 

With image eclipse-temurin:21.0.5_11-jdk-alpine:
/__cacert_entrypoint.sh: exec: line 114: illegal option --

With image eclipse-temurin:21.0.4_7-jdk-alpine:
/__cacert_entrypoint.sh: exec: line 104: illegal option --

Docker version 26.1.3, build b72abbb

Docker Compose version v2.29.7

**Comment by gdams** [comment]
> Potentially related to #642 which is being called out in the release notes as resolving an issue relating to `__cacert_entrypoint.sh` although since you're using the 21.0.5+11 image I would expect it to have been resolved.

Unlikely as it's also broken in `eclipse-temurin:21.0.4_7-jdk-alpine`

@daventt can you give me a simple docker-compose file that I can use to recreate your issue?

I've been testing with this and it's running just fine:

```yml
version: '3.8'

services:
  test-app:
    image: eclipse-temurin:21.0.5_11-jdk-alpine
    command: ["java", "-version"]
```

```bash
docker compose up
```
